apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-service-postgres
spec:
  serviceName: user-service-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: user-service-postgres
  template:
    metadata:
      labels:
        app: user-service-postgres
    spec:
      containers:
        - name: user-service-postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: users-postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: users-postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
