apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      pod: backend-pod
  template:
    metadata:
      labels:
        app: backend
        pod: backend-pod
    spec:
      containers:
        - name: backend
          image: dmitriyf7498/kube-spring-boot-demo:1.1.4
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-svc:5432/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
